FROM python:3.9

# Install build-essential package which includes make
RUN apt-get update && apt-get install -y build-essential

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN export PATH="$HOME/.local/bin:$PATH"

# Set working directory within the container
WORKDIR /app

# Copy requirements file
COPY requirements_dev.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements_dev.txt

# Copy the rest of the application files to the container
COPY . .