name: Python package
# on: workflow_dispatch
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'
      - name: Install dependencies
        run: python3 -m pip install --upgrade build twine
      - name: Build
        run: python3 -m build
      - name: Publish to PyPI
        run: python3 -m twine upload --repository pypi --username crv --password ${{ secrets.PYPI_TOKEN }} dist/*
