name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.1.4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.8.1"
          poetry_version: "==1.6.1"
          poetry_install_options: "--without dev"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
