name: Python package
on: workflow_dispatch
# on:
#   push:
#     tags:
#       - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v4.1.4
        with:
          python_version: "3.8.1"
          poetry_version: "==1.6.1"
          poetry_install_options: "--without dev"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
